### ISSUE TITLE
fix: PROJECT file is not updated with all resources

### ISSUE THREAD

**Issue by scottd018** [nukleros/operator-builder#49]
This specifically applies to a collection.  Standalone workloads are added just fine and any followon workloads are added fine as well.  Given the following PROJECT file in the root:

```yaml
domain: mydomain.com
layout:
- go.kubebuilder.io/v3
multigroup: true
plugins:
  operatorBuilder:
    cliRootCommandName: opctl
    controllerImg: ""
    workloadConfigPath: .operator-builder/workload.yaml
projectName: myoperator
repo: github.com/myproject/myoperator
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: mydomain.com
  group: custom
  kind: MyResource
  path: github.com/myproject/myoperator/apis/custom/v1alpha1
  version: v1alpha1
  webhooks:
    conversion: true
    defaulting: true
    validation: true
    webhookVersion: v1
```

When using a collection, only the top-level collection is added.  The components should also exist in this file.  This helps when we get to the point where we need to create webhooks, as the `create webhook` command needs to know about the project metadata.
