### ISSUE TITLE
bug: error thrown when resource manifest includes trailing yaml separator

### ISSUE THREAD

**Issue by lander2k2** [nukleros/operator-builder#53]
When running the create api command, if one of the manifest files listed under `spec.resources` in a workload config includes a trailing yaml separator like this...

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
---
```

... it throws the following error:

```
FATA[0000] failed to create API: unable to run pre-scaffold tasks of "workload.operatorbuilder.io/v1": unable to scaffold api for .operator-builder/workload.yaml, unmarshalerDecoder: Object 'Kind' is missing in 'null', error found in #4 byte of ...|null|..., bigger context ...|null|...; error processing manifest file - unable to decode object in manifest file .operator-builder/addons.nukleros.io_ingress/service.yaml; error setting resources for workload ingress-component; error processing `create api` subcommand 
make: *** [Makefile:24: operator-create] Error 1
```

We shouldn't throw an error in this situation.  Furthermore, the error is pretty puzzling.
