### ISSUE TITLE
Allow source code file name specification

### ISSUE THREAD

**Issue by lander2k2** [nukleros/operator-builder#58]
In some cases, source code filenames for child resource definitions are long and superfluous, e.g. `nginx_manifests_deployment.go`

Propose adding a method to configure source code.  Something like the following as an optional alternative to the `resources` field:

```yaml
  resourceSpec:
    - manifest: nginx/manifests/deployment.yaml
      sourceFile: nginx_deployment.go
```
